
# For zaal met de grootste capaciteit
# We moeten ervoor zorgen dat wij de zalen van groot naar klein in de classes indelen

for i in range(len(zalen)):

    # Hier moeten wij ervoor zorgen dat we 1 voor 1 de zalen van zalen[i] afgaan
    # Dit doen wij door de HCs, WCs en practica in te delen

    for j in range(len(vakken)):
        if (zalen[i].tijd1 != None):
            zalen[i].tijd1 = vakken[j].vaknaam
            if vakken[j].hoorcollege1 is not None:
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd2 != None):
            zalen[i].tijd2 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd3 != None):
            zalen[i].tijd3 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd4 != None):
            zalen[i].tijd4 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd5 != None):
            zalen[i].tijd5 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd6 != None):
            zalen[i].tijd6 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd7 != None):
            zalen[i].tijd7 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd8 != None):
            zalen[i].tijd8 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd9 != None):
            zalen[i].tijd9 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd10 != None):
            zalen[i].tijd10 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd11 != None):
            zalen[i].tijd11 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd12 != None):
            zalen[i].tijd12 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd13 != None):
            zalen[i].tijd13 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd14 != None):
            zalen[i].tijd14 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd15 != None):
            zalen[i].tijd15 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd16 != None):
            zalen[i].tijd16 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd17 != None):
            zalen[i].tijd17 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd18 != None):
            zalen[i].tijd18 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd19 != None):
            zalen[i].tijd19 = vakken[j].vaknaam
            vakken[j].hoorcollege1 = zalen[i].zaalnaam
            j += 1
    for j in range(len(vakken)):
        if (zalen[i].tijd1 != None):
            zalen[i].tijd1 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd2 != None):
            zalen[i].tijd2 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd3 != None):
            zalen[i].tijd3 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd4 != None):
            zalen[i].tijd4 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd5 != None):
            zalen[i].tijd5 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd6 != None):
            zalen[i].tijd6 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd7 != None):
            zalen[i].tijd7 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd8 != None):
            zalen[i].tijd8 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd9 != None):
            zalen[i].tijd9 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd10 != None):
            zalen[i].tijd10 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd11 != None):
            zalen[i].tijd11 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd12 != None):
            zalen[i].tijd12 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd13 != None):
            zalen[i].tijd13 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd14 != None):
            zalen[i].tijd14 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd15 != None):
            zalen[i].tijd15 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd16 != None):
            zalen[i].tijd16 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd17 != None):
            zalen[i].tijd17 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd18 != None):
            zalen[i].tijd18 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd19 != None):
            zalen[i].tijd19 = vakken[j].vaknaam
            vakken[j].hoorcollege2 = zalen[i].zaalnaam
            j += 1
    for j in range(len(vakken)):
        if (zalen[i].tijd1 != None):
            zalen[i].tijd1 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd2 != None):
            zalen[i].tijd2 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd3 != None):
            zalen[i].tijd3 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd4 != None):
            zalen[i].tijd4 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd5 != None):
            zalen[i].tijd5 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd6 != None):
            zalen[i].tijd6 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd7 != None):
            zalen[i].tijd7 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd8 != None):
            zalen[i].tijd8 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd9 != None):
            zalen[i].tijd9 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd10 != None):
            zalen[i].tijd10 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd11 != None):
            zalen[i].tijd11 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd12 != None):
            zalen[i].tijd12 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd13 != None):
            zalen[i].tijd13 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd14 != None):
            zalen[i].tijd14 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd15 != None):
            zalen[i].tijd15 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd16 != None):
            zalen[i].tijd16 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd17 != None):
            zalen[i].tijd17 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd18 != None):
            zalen[i].tijd18 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd19 != None):
            zalen[i].tijd19 = vakken[j].vaknaam
            vakken[j].werkcollege2 = zalen[i].zaalnaam
            j += 1
    for j in range(len(vakken)):
        if (zalen[i].tijd1 != None):
            zalen[i].tijd1 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd2 != None):
            zalen[i].tijd2 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd3 != None):
            zalen[i].tijd3 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd4 != None):
            zalen[i].tijd4 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd5 != None):
            zalen[i].tijd5 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd6 != None):
            zalen[i].tijd6 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd7 != None):
            zalen[i].tijd7 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd8 != None):
            zalen[i].tijd8 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd9 != None):
            zalen[i].tijd9 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd10 != None):
            zalen[i].tijd10 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd11 != None):
            zalen[i].tijd11 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd12 != None):
            zalen[i].tijd12 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd13 != None):
            zalen[i].tijd13 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd14 != None):
            zalen[i].tijd14 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd15 != None):
            zalen[i].tijd15 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd16 != None):
            zalen[i].tijd16 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd17 != None):
            zalen[i].tijd17 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd18 != None):
            zalen[i].tijd18 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd19 != None):
            zalen[i].tijd19 = vakken[j].vaknaam
            vakken[j].werkcollege1 = zalen[i].zaalnaam
            j += 1
    for j in range(len(vakken)):
        if (zalen[i].tijd1 != None):
            zalen[i].tijd1 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd2 != None):
            zalen[i].tijd2 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd3 != None):
            zalen[i].tijd3 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd4 != None):
            zalen[i].tijd4 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd5 != None):
            zalen[i].tijd5 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd6 != None):
            zalen[i].tijd6 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd7 != None):
            zalen[i].tijd7 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd8 != None):
            zalen[i].tijd8 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd9 != None):
            zalen[i].tijd9 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd10 != None):
            zalen[i].tijd10 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd11 != None):
            zalen[i].tijd11 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd12 != None):
            zalen[i].tijd12 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd13 != None):
            zalen[i].tijd13 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd14 != None):
            zalen[i].tijd14 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd15 != None):
            zalen[i].tijd15 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd16 != None):
            zalen[i].tijd16 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd17 != None):
            zalen[i].tijd17 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd18 != None):
            zalen[i].tijd18 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd19 != None):
            zalen[i].tijd19 = vakken[j].vaknaam
            vakken[j].werkcollege3 = zalen[i].zaalnaam
            j += 1
    for j in range(len(vakken)):
        if (zalen[i].tijd1 != None):
            zalen[i].tijd1 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd2 != None):
            zalen[i].tijd2 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd3 != None):
            zalen[i].tijd3 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd4 != None):
            zalen[i].tijd4 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd5 != None):
            zalen[i].tijd5 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd6 != None):
            zalen[i].tijd6 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd7 != None):
            zalen[i].tijd7 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd8 != None):
            zalen[i].tijd8 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd9 != None):
            zalen[i].tijd9 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd10 != None):
            zalen[i].tijd10 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd11 != None):
            zalen[i].tijd11 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd12 != None):
            zalen[i].tijd12 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd13 != None):
            zalen[i].tijd13 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd14 != None):
            zalen[i].tijd14 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd15 != None):
            zalen[i].tijd15 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd16 != None):
            zalen[i].tijd16 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd17 != None):
            zalen[i].tijd17 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd18 != None):
            zalen[i].tijd18 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd19 != None):
            zalen[i].tijd19 = vakken[j].vaknaam
            vakken[j].werkcollege4 = zalen[i].zaalnaam
            j += 1
    for j in range(len(vakken)):
        if (zalen[i].tijd1 != None):
            zalen[i].tijd1 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd2 != None):
            zalen[i].tijd2 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd3 != None):
            zalen[i].tijd3 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd4 != None):
            zalen[i].tijd4 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd5 != None):
            zalen[i].tijd5 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd6 != None):
            zalen[i].tijd6 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd7 != None):
            zalen[i].tijd7 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd8 != None):
            zalen[i].tijd8 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd9 != None):
            zalen[i].tijd9 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd10 != None):
            zalen[i].tijd10 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd11 != None):
            zalen[i].tijd11 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd12 != None):
            zalen[i].tijd12 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd13 != None):
            zalen[i].tijd13 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd14 != None):
            zalen[i].tijd14 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd15 != None):
            zalen[i].tijd15 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd16 != None):
            zalen[i].tijd16 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd17 != None):
            zalen[i].tijd17 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd18 != None):
            zalen[i].tijd18 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd19 != None):
            zalen[i].tijd19 = vakken[j].vaknaam
            vakken[j].practica1 = zalen[i].zaalnaam
            j += 1
    for j in range(len(vakken)):
        if (zalen[i].tijd1 != None):
            zalen[i].tijd1 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd2 != None):
            zalen[i].tijd2 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd3 != None):
            zalen[i].tijd3 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd4 != None):
            zalen[i].tijd4 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd5 != None):
            zalen[i].tijd5 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd6 != None):
            zalen[i].tijd6 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd7 != None):
            zalen[i].tijd7 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd8 != None):
            zalen[i].tijd8 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd9 != None):
            zalen[i].tijd9 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd10 != None):
            zalen[i].tijd10 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd11 != None):
            zalen[i].tijd11 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd12 != None):
            zalen[i].tijd12 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd13 != None):
            zalen[i].tijd13 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd14 != None):
            zalen[i].tijd14 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd15 != None):
            zalen[i].tijd15 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd16 != None):
            zalen[i].tijd16 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd17 != None):
            zalen[i].tijd17 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd18 != None):
            zalen[i].tijd18 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1
        if (zalen[i].tijd19 != None):
            zalen[i].tijd19 = vakken[j].vaknaam
            vakken[j].practica2 = zalen[i].zaalnaam
            j += 1


    # Hier moet een functie komen die dit vervangt, uiteindelijk is het de bedoeling
    # dat de loop eerst alle tijden afgaat van een zaal totdat alle tijdslotten
    # bezet zijn.
    # Dan deel je eerst alle hoorcolleges1 in, daarna de hoorcolleges2, daarna werkcolleges enz.
    # Het moet uiteindelijk zo'n vorm hebben deelIn(input) *weet nog niet precies hoe maar komt goed
    #
# Om het uiteindelijk uit te printen, kunnen we voor nu zoiets gebruiken:

for i in range(len(vakken)):
    print(vakken[i].naam)
    print(printSchedule(vakken[i])


def printSchedule(vak):
    timeSchedule = []
    timeSchedule.append(self.tijd1, self.tijd2, ENZOVOORT)
    return timeSchedule
